### ISSUE TITLE
[Question] Source Organisation

### ISSUE THREAD

**Issue by vibhatha** [Automunge/AutoMunge#1607]
I saw a talk about the Automunge on Data Centric AI workshop in NIPS. Just taking a peek at the code. 
I was going through the code and I noticed that the source is just a single file. Any specific reason for this?

**Comment by gatorwatt** [comment]
Hi, thanks for reaching out. The single file format aligns with our development workflow and rollout validations methodology, and also makes sense with the way the API is channeled through two master functions. We have not had any issues originating from the practice so far, although if the need arises the organization of code is already somewhat modular to the point we would know how and where to split between files.
