### ISSUE TITLE
pandas depreciating .mad

### ISSUE THREAD

**Issue by gatorwatt** [Automunge/AutoMunge#1608]
appears that pandas will be depreciating .mad (median absolute deviation) starting with 1.5.0
pandas.Series.mad

see e.g.
https://github.com/pandas-dev/pandas/issues/28995
https://github.com/pandas-dev/pandas/issues/11787

We currently collect mad in some of our drift stats as well as the transform built off of _process_MADn / _postprocess_MADn / _inverseprocess_MADn

this will need update when pandas rolls out 1.5.0, I think expectewd in September 2022

**Comment by gatorwatt** [comment]
scipy stats has an alternative, i just don't know if worth the extra import

from scipy.stats import median_absolute_deviation

**Comment by Automunge** [comment]
resolved with 8.30
