### ISSUE TITLE
Possible date-time encoding feature?

### ISSUE THREAD

**Issue by solalatus** [Automunge/AutoMunge#79]
AutoMunge is a great idea! I love it!

Did you think about adding some more interesting encoding for time based features?
Something like [here](https://ianlondon.github.io/blog/encoding-cyclical-features-24hour-time/)

I think it would make sense in time series cases!

What's your take?

**Comment by solalatus** [comment]
Maybe even in combination with something like [this](https://github.com/humangeo/DateSense)?

**Comment by Automunge** [comment]
Thanks for the article links. New time series encoding rolled out in 2.47.
