### ISSUE TITLE
Onehot encoding enhancement

### ISSUE THREAD

**Issue by solalatus** [Automunge/AutoMunge#80]
In some cases, onehot encoding categorical variables may hurt performance in tree based models. For some alternatives see
[here](https://towardsdatascience.com/one-hot-encoding-is-making-your-tree-based-ensembles-worse-heres-why-d64b282b5769) [here](https://medium.com/data-design/visiting-categorical-features-and-encoding-in-decision-trees-53400fa65931) and [here](https://towardsdatascience.com/smarter-ways-to-encode-categorical-data-for-machine-learning-part-1-of-3-6dca2f71b159)

Maybe it would be worth incorporating them.
What is your opinion?

Thanks!

**Comment by Automunge** [comment]
Thanks for the article links. New binary encoding method available in 2.47.
